### ISSUE TITLE
Crash when clicking the icon

### ISSUE THREAD

**Issue by ptrcnull** [AnaghSharma/Carol-Xamarin#14]
### The unexpected behaviour
Crash

### Steps to reproduce
Launch Carol, click the icon in the system bar

### Your system configuration
macOS High Sierra 10.13.4
iMac (Retina 5K, 27-inch, Late 2015)

Stack trace:
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Carol.ViewController.FetchLyrics () [0x00041] in <7e612b6f1f09458eb148a1bf6fdb3349>:0
  at Carol.ViewController.ViewDidAppear () [0x00006] in <7e612b6f1f09458eb148a1bf6fdb3349>:0
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_CGRect_IntPtr_UInt64(intptr,intptr,CoreGraphics.CGRect,intptr,ulong)
  at AppKit.NSPopover.Show (CoreGraphics.CGRect relativePositioningRect, AppKit.NSView positioningView, AppKit.NSRectEdge preferredEdge) [0x0003c] in <22dc6c9b8fb74f9892fdf7037c2f36fa>:0
  at Carol.Helpers.StatusBarController.ShowPopover (Foundation.NSObject sender) [0x00022] in <7e612b6f1f09458eb148a1bf6fdb3349>:0
  at Carol.Helpers.StatusBarController.TogglePopover (Foundation.NSObject sender) [0x00015] in <7e612b6f1f09458eb148a1bf6fdb3349>:0
  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in <22dc6c9b8fb74f9892fdf7037c2f36fa>:0
  at Carol.MainClass.Main (System.String[] args) [0x00005] in <7e612b6f1f09458eb148a1bf6fdb3349>:0
```

**Comment by AnaghSharma** [comment]
Hi @Bjornskjald, I am aware of this issue. And it lies somewhere in the execution of AppleScript to detect the currently playing track. I tried to debug it in the past but could not find where exactly the problem lies. I will try to fix it. Meanwhile, you can try restarting iTunes/Spotify to make it work.

**Comment by TheBreznsoiza** [comment]
No chance to get it to work on Mojave 10.14.3 just a transparent popover bubble

**Comment by AnaghSharma** [comment]
@DasBlatz Yes, it is having some issues on Mojave but I am not able to reproduce it and figure out what could be the problem. Working fine for me.

**Comment by TheBreznsoiza** [comment]
I downloaded the older version 2.0 and installed this above 2.1, 2.0 works fine ONCE show me the lyrics preview, now it's broken again on both versions.

<img width="432" alt="v2 0 once" src="https://user-images.githubusercontent.com/398669/53572065-aa39d600-3b6a-11e9-83df-d4cf6804062d.png">
v2.0 once it runs fine, after relaunch again broken

<img width="432" alt="v2 1 and 2 0 broken" src="https://user-images.githubusercontent.com/398669/53572093-b9b91f00-3b6a-11e9-8605-5730f7c21a2a.png">
broken both 

<img width="568" alt="v2 1 menu clickable" src="https://user-images.githubusercontent.com/398669/53572124-c9d0fe80-3b6a-11e9-9c14-fb568a10dee9.png">
funny, buttons on it are still working an clickable

**Comment by AnaghSharma** [comment]
@DasBlatz Guess, I will have to re-write it (in Swift this time).

**Comment by tsm121** [comment]
Can confirm the problem @DasBlatz describes. It hasn't worked once for me on 10.14.3. Too bad, I was looking for a good alternative to MusixMatch, which is horrible on MacOS.

**Comment by AnaghSharma** [comment]
@tsm121 The only reason that I am not re-writing it for macOS Mojave is the lack of an API. I am using Musixmatch API which shows only 30% of lyrics unless I pay at least 1000 US Dollars a month. I want to re-write it because I am not able to reproduce this issue which is bugging a lot of people.

**Comment by MaeseppTarvo** [comment]
I had no issues on Mojave but today updated to Catalina and have the same issue sadly. But I totally understand why you are not very happy to rewrite it 😄 Should be paid app...

**Comment by AnaghSharma** [comment]
@MaeseppTarvo I am aware of this issue and trying to find a solution. I am pretty sure I am going to rewrite it sooner or later because it is facing issues since the release of macOS Mojave. Also, I am not sure if people would buy an app which shows them only 30% of the lyrics.

**Comment by AnaghSharma** [comment]
@DasBlatz @tsm121 @MaeseppTarvo I have re-written the app for macOS Catalina and it now shows complete lyrics for most of the English songs. The first version works fine but need to add a lot of things. Also, this time it is a paid app - [Buy Carol for macOS Catalina](https://gum.co/jTGQEa).
